version: '3.1'
services:
  postgres_db:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./dbfiles:/docker-entrypoint-initdb.d
      - /var/lib/postgres_data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER: billingapp
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: billingapp_db
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    depends_on:
      - postgres_db
    ports:
      - 9090:8080
  billingapp-back:
    build:
      context: ./java
      args:
        - JAR_FILE=*.jar
    container_name: back
    environment:
      - JAVA_OPTS=
        -Xms256M
        -Xmx256M
    depends_on:
      - postgres_db
    ports:
      - 8080:8080
  billingapp-front:
    build:
      context: ./angular
    container_name: front
    depends_on:
      - billingapp-back
    ports:
      - 80:80